name: mospy
channels:
  - astropy
  - conda-forge
dependencies:
  - python=3.6
  - ccdproc=1.3.0
  - astropy=2.0.3 
  - ipython=6.2.1
  - matplotlib=2.1.1
  - numpy=1.13.3
  - pyqt=5.6.0
  - pytz
  - pyyaml=3.12
  - scikit-image=0.13.1
  - scipy=1.0.0
